### ISSUE TITLE
Can't connect to the p2p network.

### ISSUE THREAD

**Issue by BILLFANLL** [spacemeshos/bug-reports#7]
MacOS
spacemesh 0.1.4

Can't connect to the p2p network. Is there anyone meet the same problem?
<img width="894" alt="截屏2021-05-05 下午7 56 38" src="https://user-images.githubusercontent.com/42637312/117124707-04362600-addc-11eb-901d-50a638da1bd6.png">

**Comment by lrettig** [comment]
Thanks for the report. The testnet is currently down. Please wait a few days until we launch and announce the new testnet. Then you'll need to download the new version of the app to connect to it. Please watch our discord (https://chat.spacemesh.io) and twitter (https://twitter.com/teamspacemesh) for announcements.

**Comment by BILLFANLL** [comment]
Thanks for your reply
