### ISSUE TITLE
Rewards display incorrect timestamp

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/bug-reports#9]
**Description**
User receives a smeshing reward, but it displays the wrong timestamp. Timestamp is correct on explorer.

User reported receiving a reward at 8:41 AM, but the timestamp was a few minutes ahead: 
![unknown](https://user-images.githubusercontent.com/56118594/119545046-01a36c80-bd9b-11eb-8a90-d1825c3280eb.png)

**Comment by lrettig** [comment]
@yaelmhoffman what happened here? User error? Already fixed?
